---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia
  namespace: auth-system
spec:
  encryptedData:
    password: AgAf5q7O4KcBocej43Kg4bgAeJaNRWnORDleLro60RPeB3ZDaNwm94lqt3w9vaMUF2KfYBiA2TLlMEkleGpDjRfug6glIdu+oKxQkB/tah51/lwqegwq+qzq+rTHpMj9wpVEa78h5I5kD/domdA5yNeR5vF2LoIYvnDbX8//VXXKOvJmNKToXxLMjPeJYlhKHLJQHpHUeLpYuRrrjWahS79OianoJ/w3hk61Mnp4qLYvggyoSgG53aeGJ2heDxJ473a36FCVlGnoa4eLLAeUlIyxOHlWxQoEbTCQNTJ/4DWvewf4t3YBkr/6hnVSA7Gzxwm9wEC7m8nnJqjZX/AocQORjZpp2GSzFTBcYr2m3CmPDJEqlEl+I+gDa4tULFnlePW+nOElCQDZr7kplDLuf1d8NMfLOtKvxHF1FB203wM1jFRI+bA5bEaedZcCQ61h8fXovfinVAh9ikXkZ288i2B9NH/qbPkmHjKHvWK8ns0re0FyDGstTaYojjjiXpeteeNZQqMqwl+9OVF9sX5cIgUJn5oM65PH1LzKY8Ltp5v3V7CCVoIA82wM9SEFHwuSFBuKcPqeNhzSCrwl6cmzbtzY5fWegsUYfJQDiKdZchFL+poPKQ54f3pbJVxVjkXPv8bdpKGIgrE5MQ6FCnzbSoDaWOm/G3uz0nCMl6CwWNi0k3IBrEJVxx9c5E42JM5aLNOTJdAS8DBEs2UKKSYOJIEsYu9SycgLavwuC9FgkwA6M0l0Bs+wpNHBOBXhDg/OFVszJdjKqzdmxkGwaZW53JClQ6Sk5Mg7E0Q3JZ0Y6HNKdX/hOUbKLvGMhimR6oRfAqIxSv4SXU95
    username: AgACOp8YhMfCXMcwpdRpP0UnJm7GuwdM3KhuXU7eswzq2nCn/+4RgZ/EMW+r/Ys9+XrdPN4TXuKhppBXybNIiYDxZMkIB+lNQ60kh5TqaluDHVdV3r/t30fNAC46CHhgaCRWoFzIWp6IZQlAS5HXuK4CfQo7LNdYGABOm/XY0qONFyTeDQVZlD8lnqd4bt8ksqTQUKNyc9lDUaqvK32pQrY5RKa4KbzzW0c+o6cqz/1Nudep3sg8r6ENaKHuDCQqYpsNbMZ7ohEhOChJlY5HiQIL7ena6xAm/ht8w+t1lcKduyvPchWjuZmB9wOgzr8DO1v6PyWP227gF8Z5qOmXmuchzakdY/bBVCjDc7I8PnhBSauFjP0mQjICWl+p38gExpJFwpa4Wy5aRtme44SofsdHSzGhPMYFGRTJJgwehqHD/NT/x+Hl89C9WNasqnuf9JvFFXQG/IfKGrmXeIEIzYDuT3F+uJwD9rFdY6P8sKzIDwUqAGTtIEeiZE4f2MpitzaOxKABY/KmcQ7lNhAdj6ySDGD4XLv69gTUzkmYu5b6iy2lgqp64AH/z3HmRODRtW/wrNIfsu6zuTiqqFjrC62pVMr+BAQ6ty/QWDp+Z23bplaFmy9e+63vGApC0BEMdZeES9zYam0BXJM1394DJXECdksJ6LtnM5dO9wyuHc1aAFiV6V8MRwPjavAbNE5SaqqmU9H8gsXTWA==
  template:
    metadata:
      name: authelia
      namespace: auth-system
    type: Opaque
