---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lldap
  namespace: auth-system
spec:
  encryptedData:
    password: AgBzQlx8ptvr8ugIOShSskKIweozkLbk1El6CIdDvqUdL+GBMby9D7gDjX+jgknAsqczfdCa37xU9+1qrDCFOnV+0kckyRRK43Y1wGSCeFVcYbJadvDdC6vBeEOhnJlc297b2DYC9YSM7V5tcTeberB3haX9Ryfj42aM7mv7dPsl7tG9cYc+dAtuDEv1Q84Bhv0VhYEiOYFSxo0u6Et5Uc1qSL5SKB+WGhs71EFbM8GDO6l88t9VzYYgmOOJGqRiH11clI6UXhUNFy/73SphFZ1UxndPACsquhTHMQ3PNlRtt4/cQA3nfjA4Ld8P4HNI5hYqwXVJqzpFwsSaFpaEcknXCgBXxMBKEDr52rfAqqL/I7N6RpKv0szg1tvvC/jPLxBmW0HOeAHToeOiMINSRbXa8GRxPrMr1RxfT1wLrWG7o0NWTm+ri6zrEsFLTG/wYwQFTPpPQO7+4tkS4F5Bon6eYIIF/Y8dw6floV0KBJTxT9DDORBMiOaxQDxUObWiK8WMD8KkCLm2q5fLygc9u5QBOWeUV/skVh3r9rS3wSn3fsXpHNvElbkWlLNyQyDisHTzJiUT8Tnvfo1ziL+qf/KlPp02bi+QiOAqOJbZj44RSCDEfgRGjQkmxtgvlRaEH0vnGwY4Sa1vO3FHutZkERAMnD8n7RDWYIiCKR9gVPceTZyq2z0I880Qwpgnq+oj8BRJ8ybjw1MBxU8rrIiWjpxJL8reFyBTyDqe59nbxhd4eg2dRh4BireGXayQ9LWOy+ugj5eG2y3bErSn6zFJrZz8xUoCgrd8RXvoKyIRWD/mmwxBNDKrsp4grnBbOXy15a5tq0hMxyeC
    username: AgCD9SrN0Z4KqAjM5XxTWAiq7Qm/K7U4CHqxM4HPRbJkgy4wGctPGYNt4g8p/wbLEzx5Wie1MAVvYLrLAffrqUPf67JAkY8M06wuXTy4FcCQxpGBKXHzG8tZLsoxRYRX2p696OCbBSDH/YFfYfnseYMZEbwYp83ZbCF+MCHEHyE3NIf2pXVuBHyhAXONajqNRAnwJdzCQg1BmcoQwU9jWBwseQO8ldxF8eoI9lDX4Dx6HcaMMRLSoH9l2eAKByg3X4Jw+/SDrjn+IG+yDok7sOXvJSZrHoiqF9+JL4G8XZW6Ek/VYjpN1dqmqZgFtpqvf2YYSuTWrLq9ZEQQI0yNJKJiZE0sWehxbcJDcSQtBEdO7RheNpsfPP5XxlikU96LaYIWmm+LHMdTxKlpF4bGUuGOkj08SHf6/ijOIzRrd1xSJdmHo4VYfjo/19Rgtj+qPcveHTiD0Ic0OiYyxSSZWNGyUc45eXhp9PUsvrQ9wJoH8gO5R3WwKuWVMaPdhWqmCH077VbEUMuP5VBgLbsa1MbY154eBaHOnayIpJJPDBXDwheX1E03och7YQLXfg0jrpd4h55vjCFysgxBYqZQPvSKiYStpXEeoYJflleb5Q1fcMkv0Ew9tIkE4f0FVLv6cMdu9ASEe38SpsCFP02MVuX35iLTBONv8qGDcEfJRGQwtC6/e8AVRIBlncTzpS2uCU8Ty+LIug==
  template:
    metadata:
      name: lldap
      namespace: auth-system
    type: Opaque
