---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowlarr
  namespace: media-server
spec:
  encryptedData:
    password: AgCeQMD0X5vpkJlw2WHqBs32pxXDJTIcAd9XfS4yz0a6HtJvQey4keC/0RDSswjDKTywB8TC/qHKx40BGKKbnK01jPGDH2SulatxCtcOTwwTYrErEQ+yvIPlL0vgfKF4Kr/gY1ux76bGEovC2KPrh0ENFi3LtszviO4bKBQUIKo5pelvBPfAk/aaeZiQ/zV+HrMWvu3X6K822eK+zXDr6IXfOFHDOD4ipx8w1cJbw24Rsm2eFClyNR3VoF5nLycfIKCERbDuOronWUClFGXvDT3aVTIHyswr7tC+h7oJshccxvwMlx/Ic9EbdWJFM7Vq549wF7QgCX2xIMDMFLfShq1e6ci5tAToJ3F5QklsWZ8XPQhLpglvoYBgqdtmeka+yToX6gy1cWMjjTnjO2h0XlfZlUK0jyv07QNOUUfO0LTP7Zy2KMm4bGcvIX6ZuqXC/3TWzGfECCfjuNuATDlZEJ+5+WJt2J2WBlkUTtJU5i4EGb4lRZNzUDNy0+VJ/rQyCOOCnd+v2puxo8hCZkNnKZCSRcIxduMCaTKXVo01Mml0OUAlGGsEhQ4nGNdWSXJweHarSZPQdzJZZCooarDKi4E3L142V0mJqaWhDDa2XNAjM34wPlYnn5/OVSysjd/ZOQNnhDP46hT5vfj91eP2iv2Gyl7zAItusdhBaOb+9kedmvRiVEn2GQBlpRHVULkNeSUYq/2f2xuWfdzk62l4t4TGENTQ4zhQN08eGZs0SRBCL9asDEFs/9bhip2XkAdFLKJaLx2X/2KN2C49X9r3EyyGclTCaGZTI6VSCZwPrW0kYoiEX6SkOyaJFy7EVsQnb+HlFoC0RuMy
    username: AgAIvKC13lRtJ8FsvoF5IFRvvtcOh0/lVOleuUkrcn11/gh/MCBXlg2tf70Xbfk+dtZUu2KyqhwgDwmeSgGMpsynPqw+J6CJIR5xglncsZ1zZhlUitmvHhCvdx7zjCvlkQHmXkThe/ERgM5ziQ2RhUlCw7GeptKhZgZndenrBGxl4X1xV5ZiT0mw9Ic73lbtI3cGdUy1++yb8QHhieyn0rPlu0Q+nYCS2qalOXg+K4PhHyEJFn1HNBRW2zzUHgYUud6Sxh9qZAX7ZQcg8T5Zn41gxH98Hxf0TSSwqMYXIXwJ7JqzTkHyJjNRyVSlF2kpHp3iigieFRqhCvaJPP9aW+PK9twaolznCUDSHpHfETYqRKGFac9jEJQRjyceeWTwf0fN2lPBtcGhzPxaqsB2wxqXQ14SGbwoEbvilMrucCB4TN18MqqdgayeWCVCeWy2b5TLsG3XA4w0tx1aFkK1whgjvkUeMxnGFSf852vniKHkTVEfb7Eu4/2wZ86RsjeAQSwmr15cRwSIEpiohsOxcT1ci8Qs/hTVe/UBK9fcB+Rz/zS2CesXmbwSYVb+A4lwhf9geu0l7y3YQKnRTsTyN8JqiVlyTW+CItdDbvQT23dDjPQ8mQlBOvcJlnxI0iYyVAh8CjPgslwqRNYYgqvVV0ywr+IKjqe4OT/zV0FkKbhaHR2Gyeo3ITO27tlYsiYXDaHyNZvxNyPigw==
  template:
    metadata:
      name: prowlarr
      namespace: media-server
    type: Opaque
