---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: seerr
  namespace: media-server
spec:
  encryptedData:
    password: AgANHbLB04wsD0vvIhGt5K9rwt8hpBOgIFW72cdLD1WMTYNDjOWnjJVWW9D8UVneenHPfdQoE/PN8Y2ynmuxDNdmBEN49fbj55nJCdZpolpPXXp4e2WY7Q+GP3/Nfxa/hSgENZfbr8IIZIe+PZo5JnbbM0cADfCw8i7u6VXiaYV/505JNX2EGV9rAtItjxeAq/PnZqYE8pmotuRWZ2skhnYBkyKdtOnhVVZDYKnvtyK8iGEoOVoFhmtYBHo/GsHhwnrztusJ6Hwt0gJVTEzehLRjHC1vb4KN1CLymmKSccL/oGoYV08vyOr71f6rWT0zPONEIVqLAnuReZpiKhPMU6vAQMN1SvlLwPgVV7xVuW3s4OIX8GY86mTVyaKDHkG2+w1kxlfHtLkRp/ECvMjHwNLyNU5fVg1qK7zvhEI/FMkykKNDM7VEQH2YMQ+toeHbMbvzRnG7hmsHtSzDDbldizwly7+leu4MKeE2ZLdKNdKNCduTzDIm6vidUGxWPAM/s3DNF7UnpgZHXJvIvWBHEtMvuWkBgsr4dJychxD1OrutaokEalUWo55jnOcKdoKNgn5LSa102BOYZPzo++t4Bcabc8M30Fowyvpna2ipLaF25cbC6TS/JKaEDcOc8WCIm1K02O2ENp/W5/K1zXyI1fAJ/tnqDPMhPy0I0Ass+oX82U0HrY+ak86V4OdCF0DGqi6AetiP5pDmUG3pMeBABq3v1EWQo8KKZeZPqOHUzRaHIIijRD2Otq43BLZFlWS3F4EcnDOWMqS3f3JSqf5Vx8jpaxqYNae1Rmix5ULavdhjHYWqbSNir48tom9gbjZ2NxXfhzrgDEkn
    username: AgB7Tj48YKmYMcsOtXNKgosb0kEqDaJUy3ClgOXZewxKnKcU6eJIwu8E3gJiB7XWYvtQgP1fxxF22Ulltu9TW7QeI14ZPsCfQ0+i1ofTCPvNaS9mcaGSZxkjLSdwTwdV+GHIiqgMlvpufbBE4/nox+xDzGSLmT7mXWpRCffEImb/XT8smJdKO8ISzsbkzuvzXCms8Q3DZ5+vS7oAmA/UQvNwywFeY4dnrbRejNaEhuyt7DH0J98fzICS03NefYhbfE3fbOmmBhiuQdEQHG0GxuOBwsYRjNi/hoftSfpbcdWaWcqOpDwzc5f2kKFOcHz5kSVFRLjpXkqHxtX/G9Pz9ow2qkLDKbKqUPnTKzy/XN2UD8PHLJU1QXNPX0dHQ4Hm+PdmYlGdeL/g5pXTWPPZBYrcfJL8Mvp1kVlnZHYXOMaPU585OP+SLuRYuRbYLOvXyeuonAPOiwxwSbgUC8WDr7qXqwAXDpLoAbdK/8HQe5TYc3qds9tZvUzEAqa+KHbYZrr2HxITc1ssseaSCK4PhuyfjLquxlA3J9Pcb9MIWZJNuqXnSUk3DSAYdcP5mrxg2lo35TdI2nhPcJhDDAO/HX5g+RygK64uYhQwz0ViRgIg03KscOAWitEKXUgwRg8TFDfgYpyJ7Gqg1eirhu6eroT+OxJIx9tWJEj2IUVu5UW56YJ7VOaDFCshX6vz7k3C68BdZ1hrOw==
  template:
    metadata:
      name: seerr
      namespace: media-server
    type: Opaque
