---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarr
  namespace: media-server
spec:
  encryptedData:
    password: AgAd+14c33PlLzViawMBzOh3URhmon+rCeEYV2P9sCKxeMjS/Vne+mfQ61RKDHHTA7IP/sjWnc5GiNGqi23r3zOKHCtwyl/Le01971pghYErYnNi8GNnGuSrXyiOz4RgYEm1FpIqc2IY8qQeixoF/jvhkSf00a4PmFJpSZBF1X1rT9mnvs09h8AIaN6owlhSmQEPSBz3Uz0UwP/qnaYjK2tTZZoh44tBSED3nYuWLNPn7GADL721dforvFfSkyhS37zbWqt7xaFdF/VSgqRVXkGsEu4rEHSIiq4xxzRUlcKW553y6QBgewwF9J2Z6MCl1rC+PCmefUAz4VDRlQW5zsyZeu6EPE7hynefUO4oWFyWnrlDHRKS4xTQuXWvOqPc5qoAlQdyvBm1/GGEW1m7X8KSAOA9GdHDlLh/Hx2gFRc0w0Aex5gQRA5+O0dTgVMwHEUauIohTg6FWGCRe2hIPAot64+R7ZlwvxnESTwqHvABVkU1+O4esREpkRxvXgMy7aZIbSFLAuQGLIKVtSKAQkl88fuyMF1B0+1S3HN6u8rQt5tHiT9FmLbsK9jFxn4W5xcgAAvCHuGYpwUrmASwu14DhXLi9fzH7A3i/WB97okj0hOrkOarEDh+dwowYhVSinRsNfB4bDMRUOGvBnNDZzFYv3b/Fy7YVo+368hFqP8apEBqblTEx0vI2DB2s9zkiSe+ueDyuAxtArdkYJV8d4HKrefft+7wIeGpYMdHZs/RsQZ9GVXlKELftTA2aX8ffu894CzBmw4GYc7YAYk5XENwKkjoOVylZqHXzC0g1r+c6JT7pHfXKui+dxgC5cdRpO6Vf270tsIF
    username: AgB/sOWrnZAn5DHKtSaEwyzNrXRVJEChd2ArWrjaenE4UHu1crRX2V64UNJdowj9tJo+oiTO2cKZu3ZmFampVWItydG2lYdWUJzXpBDM8/ZVQX1WT1FzPLjgsHLqZiuzvHxssOfJ5IG/5Vw/EeWrcFP1I8PutCj/1TRvsPIxmGR6AqRn+Sk5vyClSYf5mGKppfG8+0FmT2B3C9MY1NvLpZ3acmA3InPpXHenpUzG0C1BiJl78iFarBdrNof5u+3cZ1U6WhCtciY9X5PmjRZQw977CMgcujFEyac7+zoxXm9wm2Z1cRwhWwS34fdvs5mrZpGKhtI+ee8P+uO22VW6UQaf1XdwsiWMBrNa6gZYffCV9XN9d4M3/mhGCK/4eRGxsQFuHNQjZukgP3bw+dD3eTNE/ZCwAUrzly3GjqA/Y/Y8xDRsTuXeMA/YTc03kDYG3TZRjbY2l+WmiMswK1j9jxTIS9eFjlUJCS/PhZLD4LL9R0geZnsMgNWHItXIUJuY2VUX2gUKFd/xT6AIbbJ64M0hJYX4FfAQIs8NTwu3nxFU8WlhAGN//geWjWjjRWajCE0zCHkamF62ULWQw8u+Xej6NWll37pIFXujJN0QTmYWVpKJwC8To5wMsCeEoaNFZ8JjL0jNJFx76xOZ5fSxzQaH1bBxGDCQ7iTwxbobKdJjTpqdIR4OVds+HaSyQFUniwVEaBKJ7xg=
  template:
    metadata:
      name: sonarr
      namespace: media-server
    type: Opaque
