apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-server-movies
  namespace: media-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Ti
  storageClassName: longhorn-hdd
