apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-server-config
  namespace: media-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
  storageClassName: longhorn-ssd
