apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-server-anime
  namespace: media-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Ti
  storageClassName: longhorn-hdd
