apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-server-transcode
  namespace: media-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Gi
  storageClassName: longhorn-ssd
