---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authelia
  namespace: database
spec:
  encryptedData:
    password: AgAz2g3PYUNyWXjRqZJrje8v0I2wjURAhLVCxEo9kv37ojNVk4sJz6aMN6Ln0rzPsQOCIUwV/LVPq5jtENFqC5BaLGYWvFdNU0yFrRss0/WtSZC1Vrt0K2/yzo/0l+iQUh0FYRLY83HCFtPFpVRaN1EYvRT74dBs1W/Ndx47zzRN5+9HQGN/vlOXuM4sdyYxjMtzxwUD/bLJhgQU713iyk1PL9DRhyusnGRi255BQqVPOZpqx9eNOkFR2i2bgjPI+P5Zk3efQUIEwPpnc8ajVPhQqQxixYKwjHyyelvCidWQ0fYTUKL5MHBDxMTrUvxJ6dMWU3f7shx/+TupQC/LjjUG1YldessNMr2ha+3qbDZF978TRfPO9k3/a1oj7gDbT+wNjvfMi89HKOtdomdju8Ii9psxkSbTQFXqdQGYyRDyvk5re4yHeQPImtc4FDLNUSCqmtNHB6hqVhhXcikqepNw6+t5FznZwJJyP4YPliSwLjD6jtAAAOj1TgisHh/drSijHoqrtq+KdA2MYiONo5tvN+DjMgC8moP7chb5u+luhWuUgXonYIfIQOtFn43FVXGtERJ4xf/2zSd6JEM+lMR1U8R6FJX4P4mRGlXr4nhB5aTbpdceH6/hqv1XJougiVhlqNomECj50jpDVpSKzsId+W0ULzl+cUCUa36IoK6vLKW4Rq+x4+91rWOYwHAURH+ArtiE9pwryTqbwdOCeiTpx+jPaebRzkleeF8ATglVUL5QuZdqCxQDP4IaSaE4k49aXcjPAgtOx8hvEEyAVo3Lnxiyr4SuY+EIodRlUHeLcw2EwqeweJ0sXevXGyynVndqfgtKjMUu
    username: AgCfJIJG2A9Koq+KA5jfqfqZsIbzpWDCMj7JYTRis44ZkV6YtTK4iupo6CnNcOJqfAFnFJeamLb4G7W5+OKQK2cMcdfxGvS+13ynip7QmSaKYEn3uoqyGE2z5ocvpxKsdRR+hXstr3G2T3sPjY/DEe6kGrRrhpiZNEMLiJtxaEvU6bcm1sVWiWlIZ3xqpmoyfS93blnohoBWOjDT25iLn9fLzJ8di6/cIczN+GsP/b7RIzx9NN2BJVEH20LoqI28oAvnfXOqE78L0nUK0MbG2/DLTD+8OkLLq9jss1B3uLLm8CXdxjUE7VxIwuhly8Bk2IUAvsLy+shNaOx1Ggb4gJgtZqz4Sa8vvgvszKsBoi9ePFQTSnVx1O+DPbp6ri2a4FkAy2695fVFrbzoGDGzq/DQfTrLuF2iEZPwk68Xmd06dacPoWqtpu8GyezlxkaO6oFBSLeLxKY+Ch4qHLyPwI25ASKF8Bw74+1oIaYNixktTgho1xleDcm4NTjwoRRSkLK9Ii9WEjOySbuQ/noDaywie/onFq4DqbA9l2bJZHwHi7FKX+l2Q9ZRjauAYMa1Pxkci7y6suPsrFPHvTLKKfnvcf3ycXaAbGPIgS3Fk5uneSI9Xq9Gla7+NjWum/3iNXmEommWxGEDnsKi7KxVNTX1hcvbNVJh1eE2zBlr2z593PPIKnur9HPOAd9KVK3TMoynBJORQxunmg==
  template:
    metadata:
      name: authelia
      namespace: database
    type: Opaque
