apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: kgateway
    app.kubernetes.io/name: kgateway
    kgateway: kgateway
  name: kgateway
  namespace: kgateway-system
