---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: network-secrets
  namespace: network
spec:
  encryptedData:
    cloudflare-api-token: AgAz63Ym4uc1TYwgmlwsptWiRhtGqUcBd5vWk0S8Lq3JAUHq9dqbKy/FATwq6abpFAElrAgSg82c4x9L4X6Qq3PD+4et90MGb9QK+/KTyZaaNIt0kBUE3tMMUQ/NJHE2g6nTRvlELiGwDX8IzjyJASllHePfMhyqhmHRaSRhIQF8teVZarvtINl93NmFlMKhfKTKKHkDh8d0t0x7OiirOldKFef6HKIrQPkQc8EtUdhN1ByomO5t1vHiYS57p+FyuoOHZnjcMUmQ1G8FtP7fpBmES6x0avGpGdGYQptzjdMw3RzQHYAFg4XcHr5UDR9ycg/QgFYY0l1QPazia+JJNM+7hdRfPOHjOUEwpFsad40rur6MFe0/Q4BWOjHiOch4QVX4+TUdgbo/zI8j+qi9IxdW5YyzMceTmlSe3RXr/WhwLtvlCI1N0Mfsb4554kbW3lZ3ql4dB3B86QC7LYwQKFgHRVD/h0suQ/WpG8ay4gMWXG6KhWOMekrK21wUmI3LiLDDvdqvvZyUvdYdNEnwBLwNHPbB/1x+LI1m18BYdu0o8dGJ7051K5cCQlRXC1SylIpyTajPy+Jz37oodsZOZ4FzLviQdVj94PKWFMctgZWzW8C0yNn96Fx3339rVx6ERM+Q+1RKeM9VNCkyqy+H8+i/w7Kq2fSmvut0fLxVTG6gNITZjwlQ/JH1cQHb0vuXEybGphlfmbmLoXALj1p7IEDNQ068uaGhs1FrNxxxCfgeW00sRZ+7JEbO42T4jGEqurxgPuM4YQ==
  template:
    metadata:
      name: network-secrets
      namespace: network
    type: Opaque
