---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: kgateway-system
spec:
  encryptedData:
    api-token: AgBiWR4zNkH8ZvxA4fddfjwO27/Axmh9pUfCJzFvJV0k1sIJ51BJz2xuE7rrHgwdFmS+fzQxX2MGcM+D6Ivv0esaOhAos0AEmJWaqa68w5u2koeDuNPRTQH5mJsG9v4Jc0SHcPUs23gZkuX5MVOUen2J73yeBKMzC+nhDdmRjHxaU3do4wj7jCoRdUQJGTldwcGf+F+mgClalpVgNaGmlGB/loErhL280pHdxzxbSfds5gx6Tr0Xp9mVnfTkWxc/7XnFnQI+7UTGzeoiCH2Q85TGafCFTM72ygz0ilR8aMW+ELXnhHRnmfD5YRVPL6hyFHz+vSOZAT/W3N2V9Q4brPblTLNQcb7eqnbeWhgbZX38cybzydPjwHsZbo74tgcBhU9YWZfw7iG4PRFwo+K9iiLrnIfn9PuQWH+0OOfxHOiBgrsdFe9cmdzJLJpDzDNzYImxSY6r3NOzOxOIZjXtVGSz+hDdarRznnWmjrg1hNXww0FISa/RkVxD+WzZKtLRb4IlnVh/BmbyuubcuZwNT4o4ruXC8oJL3g/B83G9bdvb7+xK94J2Z8iBNu6LDtoh3eEBMj6jVazdn5N86jNFFxQHlF6w/hvjMJmJtTgVXq+AagbBOEmG9zcMjA2NGZIV2AcI0UOq1rfdnM3ptQ1L9nhuI1++Bgs9MwI8uMyiNhb2baCdHaIebEXMJ9AWbnJAJ1MsFggtaTShx4azjduztQ4tE2jL9XZc+5MudoLfCrF1xEhHq0gftvujpPOA18x0o199L3aRpA==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: kgateway-system
    type: Opaque
