---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: network
spec:
  encryptedData:
    api-token: AgCIRJD5hu84KMqcyvOeyn+cxJiDhF/VNSgkap5CdxLNkW5B3obI7U0jaU/qms6fznCYmAJ9riaxAe0GTMptz0b06ZA/BNNsfLYDUEB11j4yfktd1O4mfFcSGHb7U+yqmaThC2BiX8OdI/dlZK9+SV5tWuJCp8jF7lWOg8UXxcoB6XPBZVjhETNvqeiPDqnbHa8TxKKitU/m6L5aMjz4FwBwahzCkAajE5AqdNX7gM7VKvrT+L3p5LVfOxT/HsuHbTnWCDgemLNrKOqcPjFDyJ0EKhf8cqrajcTDEmcbI91RTaf9ZgNOEEAWAA3eYiUU7EGx4Yrl24k+Qt85HNv2U0SYaCgfFrcDqyul5xb+K+GAeh5TY2/UByeayqlvlj3HzpzUl2I5GS63jfavBpLJjAbbu7UF99oVvSPxhf6lPDa4ldaSo+0OkmJZdBde6NMcJwuVQKKkJTSjTe1SUSyQN8mcgWoCvXYJmHYfae4/fiFRTX+pIZQPHRnoJW4VyFsW2CMUYK/yVfJKtQSnkelvkrCB+xRg6sm6X2dYh6EiNHoYNoTdzlGLfIxcvxly5vN3Lp44aM0cbUfkWZWnxDTpwowp8V3dNo+oNxnFGlZTI2mtweddlNDEzNZqatRhWZGDRr6M2jHx+W/YJxPrBGYa9tZJmmJ9e6D9NGKLUN9rTLT1CXdI9z/oSOPvlMSo36YG9wvpp3Bkzp8Rlyqb/yEzXFcGf0vwioT3kPDdBOUPvWO5gxZ6xQGSGv/4mlAVmjyeDfB7XA3rNw==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: network
    type: Opaque
