---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: transmission-password
  namespace: media-server
spec:
  encryptedData:
    password: AgCQmEIblUYETYw7gnG9x9UNQvOvHa639Je2Nyl8UlZJvM+FV2slpCHbnrcpTsDJGQA0WCxBNaTR/Z5Eko34tfp9Z5uZ1/d3EUuF5R1+JWQk0J9SW7MDR42ttFzdmPH8fgPOy4xdH1OCYG/Tdxs3Mn43Z+UGx9B2Ykxh2wsm+tLmcwkHOzNyjO7JPBahcR89IyYheSPFvm6FTGGeWzr07jJJBHMgSBLb7JKrmD71ze2gDr5pLzZptoi5Qn6XK5zSywylqrqa0CMiRWQOlxHrqjaVu0L6uuMj3Kt2TYbApuo/xvMzrBScFyHnKmtXS7FgIusvoEHPVXQC1iLSOjAMVctxEb/Dbrsvs1rqQIIrlQQK9dqZ24Yxm6ec/1SRaZH4l3lD6KUsrrqV5HDI50iye03GvPLOvhuWhos7oN+RbbZrV8p5CevbBvU0qIWEPx9Et2rBhQ8I1GA3e6mADqrfuFUYYlWVTczJ7Aj0+EHR+2M05eS7VLPqms6Qmmi/OXVhG4i7MyZD+y7Sp9kXKz88QZQ5f0F9/TwXMedGGMIz/SHTFJ6H97kmLCx2dmxas3FZ7GJFsTgHGQEjaQ/KM3Rt6SWLNb/HlrrRvJzAF7d7r2U94UNBt8VxezCzYMQLS9aBbQRTOugVKVEZPskpmpeouQ713U4k+2lW52Sfwrcf0GHc7huwsMHlZwmNlARQ43sdLWsx7uzJvd+qapABsZ8BWa0gnB3nybSh51XS2snbIKyZsQI=
  template:
    metadata:
      name: transmission-password
      namespace: media-server
    type: Opaque
