---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: media-server-secrets
  namespace: media-server
spec:
  encryptedData:
    SONARR_API_KEY: AgAalhXhhg1eVy26hpYY6nYijt6HNGJQLmJuaVBLuo5ArQOgACCJ5YbLmB5JN9MVC42SQopHete/eJgusKpSGRNKSehgcJQiIEcNJOOH6BiAfxl/f5s8vOBYlzTPZjToUJxOoLHp3uPAY+A+8E9i5QNAWkOilrIliiLxYsvDeRHwhm0R0NsUPdo5NR6UEzsdzuhdeW93gZObh4s44qLIUckby6jUKwPa2EBfaKXKw5pMb/Zfi2KuECDtEInprF4fiwj2BJ3Thf9TTEq9mPLGpLn7yHWnNEfDJC6T8VKUf3e2M4v67BjfRcoWv3jgT2P+0imvKoo1knA0nYyVww132oJ+k6ni0Lr3aY7IQcCEANNqmIYsqFHGpNyP8WAqEQ+a2j5/x+1tGCHz0/MkXIWGsEtd15ebhX59JfFkDBaJZdB4spAL2U3kNs2U78X94OCvizxiZ9cEWYCI1q/3IO9phIu1TQyiWI+y/vq4kgIQebAQJbOwl9KuE3PzHzATeZe3Fukd4V9wkE09dzdzKJO/TAtwmguJMw7wCwrxOBa8ohUsQbYXFaWkdeq8xCOtHQean++Wnb/7RfK1KvbAif0oYvdoyQWSOsm31aLF8BLGUoXHcOdMsWzHKklV6hURDaNqnSWDPAsWFOHRiKqjKK4tiZVspFwjIzY4yXmNYnZtEFNjWGBA/+lxPPfI2NMOyNerTedpXggANNXZWkjqb4wWmw/eMvLlcD8u+d0JWMcRTDJ13sC4uSt+xmDT0ELzeuVCiVfOdJH5o08yU+itdoUV8XbB4h/sPkTiD4O5BMKIVX6g5oE0kUBmumeACrxn30x46nXN8819VGTg
  template:
    metadata:
      name: media-server-secrets
      namespace: media-server
    type: Opaque
