---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: media-server-secrets
  namespace: media-server
spec:
  encryptedData:
    transmissionPassword: AgAG+e9b/0CmkyXUHt08EhQnEKgjyhNFmezILKu04VT9Qj+/WeCjDRT9PIkbX8Kmt0dROuWmq+9WNZv9ldHuEQAwn5zGtJJ+kvcMEF03XWEPvtXvu9yvpE/9TzML2IRMPapYOBUuUE3iQkAt0sxqggKMPJ5URb1o8cFu9IGRhztDBx8E3TvmQG7c69UcKqLkW3fu6rGaVni46BFgz1hhSoJfzea1bxgVx3bmrKLJiYaYt8rA7QzQ0OjBV83O+JQLsIr/xB0r5q57f22htP4RG1PFYPuHi52hMD4Le9M3KZX7yB/dYXbMNfqDWsruGVmqZwQ1eK2syqYt+2pknhUj7M92QW6bbFK8iPt4kC58aYm/DLwIgxGn4swPhmNQCTe09Qj903qiEv4lpSsuc1aakKVFRZABp9vlwbsDJQNG+bpUfqjirfsbN5BWd4WPqmUXvz/hwNz42etsyxxgDvbckkKKi3gFQFj82x5a7Ab/7lOoGjmW9NJrGQVp/YLVH7Xb3LUZcYZ4P4htg/hyoi1SXUjRV2VhSgnaGZj3SIyz0o7erEnrudCSmej4wURw2lzQz1n+gtaOFoZNSqTx6qCWF4EzUwZpoWe2j6JzgBI9R+rvlVqA6YMj73qUWxArxoEgSqsK6tPb8tKLKztTHMDEwKaDpCBfW8+3kcfAAz7JZprfd68TlyC6R7saVHbmcIxoVGA2YS4bwZNO+9b0oN2dzgABhw+YyJeCq9hvKJrYGBET6DfxOl+N1HteTWxnwjrtAJh/72FLSs4ZdPGN0mFKG3E+MsevhE52Mr1r1idWtTvdg9Y1KIQQTh1y+ZiJ7Dt58I2KMVXWoh4o
  template:
    metadata:
      name: media-server-secrets
      namespace: media-server
    type: Opaque
