name: Generate Kubernetes manifests

on:
  push:
    branches:
      - main
    paths-ignore:
      - manifests/**

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          extra-experimental-features = nix-command flakes

    - uses: arnarg/nixidy/actions/switch@main
      with:
        environment: .#home

    - uses: EndBug/add-and-commit@v9
      id: commit
      with:
        default_author: github_actions
        message: "chore: promote to home ${{github.sha}}"
        fetch: false
        new_branch: manifests/home
        push: --set-upstream origin manifests/home --force