---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: radarr
  namespace: media-server
spec:
  encryptedData:
    password: AgA8M0Tg5vGCGNKgBlc3k4tqBHaIVnHGMcTRy8Or1WdLx1k/pq8r5SrHxA67ijnb8tBekFGvXA0xmFJSwkjHkRwz1F1YW7yp+G4OV+A0D4xHxhp+NnzDlQzQToGTteU1ZpieVBDFGNhuiyPSD9I4VJbpTc37xrHXyI0pmbXyqxKvNSCqfMY9HKjdM6woNLcP8k1pPgh9Ow7jpap7ikXP4j59g2M4UIwTbiTQB6+4Zp8NbO/xXsIEt6a4n9dVJlJbu5WdmXB+57Krv8UCeCdtSbUGVmvFjmt/m7AkaBrXpPuY++B4nt9DJFtYRyKka1thMX7Ff6hsAU44YoNYUuDTZpK1rXW9W+zcxFb0nuvjGR9dyxtjcUzadhgLUkA1KGImy6wxadgGZfqme83xxbbMBmg7Zgh+sno/Wzi+Og70iKQJqFXIpbJxIPLgDiie4Z5r1wyx/N2QY2GPoM7cc/zhQnalXI92HvE+ofpwzP20gBrsW38aRSf3iL2ID9JD8mVKeAvGOFHdCQSgCq/apLWDIIUA4WfHh6IeRKYQZZiV7F9/ZKMGV12fWl5XTjBEDJhk1xampVTrsIEtq+CYRy5Wb3suCmWdnU5OvCEiLTmd3mJaLLhdma7/cJtjr3qyQXdmjn5ZL8ui2TJk4TqSpGNoufrejlMu0J+VZmBiAjZJi2jU1md/0Bb8cjvDWW/VilMJBbIMhq9UR0SMZZorfep6IJkxwlRPGkoWAUgIRI+SfWBk/OwcDArpu5y0fxCc16NUgc+//w0uFr+NqZ557Py3DoAyJ+19lfkbysrkFlRdUknzeU+OCOLHaoGcgSVUJKImEkPTuyGzUk2Y
    username: AgAIKJK+duq7vwh/DWnXoBhgXO1ewiPE3n0ntbuw/h7NxIytwM8tCw6AsgxZctZuEIm2bzVP+7DvGr9VUhCrFI2YhbTA7TKp0iRF71JiWmY442SAxeQMT+VFCP8eyqN7+Q4eAwbajrfLkzY9K1w0hyVotq5E6/llZ49ZyoNg+zIdSHjxTgZDZ/2RILnCGjRNXlcenaPaw8+5Tgd4t/8nbdft90kSznAleZK1/qOpChBHY5F60ly5gmpTsiQNblYNj/scNzvBAopRYvt0iGDDyj2+5GlS18LbpGiLtPn48Y+Puii/qR9GwGdJKvkJceFK/TIhe4w4IBpRBz8ga7WzIkDHm0dd+nUsbrVL721S09H139uzEBca+wapsFB3ihFWJbX4pnnLmX5YqEOSHsNY+zWR5WcXW3xymewPspfb5V4XqDQujDMmyEnLhe3OTgJQufl5Mt8Bwsk5XrG1WH+sUo3PN91ifbUsZZ1AmmbPcxdOFkGqn/rwbLSlqJsZyU4z+OHHCwQadTrdS5FVBviF0cso4LNYsnWvFtIHijY6YPu372FCSmvaP/eTqWYX11/KjZFmTc5GfNpqPry1YOkvJfpp/5ZvJeaBi5Ld4Kob6nrJCexiQZrh8FXw1ZsqYeKnkIHAzSDswwsgzRiaGis8GT+iOCZD1tLbVj+DER0/IQHtUG2diZqq6QTNWHMbzsiPvm0n3ZoCnfY=
  template:
    metadata:
      name: radarr
      namespace: media-server
    type: Opaque
