---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarr
  namespace: media-server
spec:
  encryptedData:
    password: AgCYiMB+rDLfTzhfdFOxmkWEyrO+4IIUxSTdHftbgcnjlc/sKgcrjUXdqJzFOyMgULiRzIbU4QWg1E40Iz6Za9eEGytcqmrgBLzMrpQ04Y1Rj2CXzOK4z0IvJkrNJEkwDVjS38Otlv3DxQw/7ZN3hdxigwtd+QxSI0rr0szFMT1c1yB9tGnspA0178so6XRBwQOAUdK3ifDQae786Ve5n/jQGFf7K3MFTTHXLsd7zXG/Nrh0Pck1DKFIloM+JY3KFLrAe0OEEju2pofTGaqTeENp82eLkDNAxIax1pTcy2ibHDHJpDRKvGdbum6VtAIdOASFhXcidNs95qJcOayClY//dDMtRsW7GhaBOm1IbkTAGvG7IsLnM29uM/AxTmxQXO1ROA+mujVFYQ65wFXeE31HKMnv+GGToCLOcBUDDDTszMh387P43edEAjAl47VZYXLmlPlaJjx6od+xiAk/JsIUQvHKJHAKDrUn/UosTfrXKqmY3gGfbrEkAP94VSRojX6yB0LN0vikSKcD7peLhbosSfLzG4oL/7pHtvnPCLCO0PHITKrY1hz2IJahnWMndHha5DkoArlyjDrEgX+CEMURJa99MQOT23ze0z/3Mau5FxzMUxTbHvZ6D7qOZvuK51BgREo6VeZIL+x44VvOzEA0ZT1vYUxyOdhYDZKPj1ZCq62/78gXGf2iYgVMxoZ6IgnOnCg+N7d4cMqq+aZ7i7NGZcMOSHX/Mrwi53nVuANLjP1dfg37OZvzOATHK2KPsYlb91xkVPt4TzPYuzw9/PFWPoeOpjiZIm0+vTVRnwoW9eR2h3vgvgQpVa2AYQI1nidXp/oF2ggu
    username: AgBb5T6R4GJfiUskPiHBwje26LT1rjrj19bJBExZscWndvrOB8q1ddJoTvO7VBd3U44Dve8kL4hngbyRfOlwzORKlPgLTNwtrS+rjPGjxyow7ZintuD+iVBxK2u573TEy7+/uPDU4Xn07DLmNKsFCKK9AO+k1v8WyVf8F8zGgHVQ7KOyK0ILQQHdAP9o8W2+8cqnD0STbJuFEHPkFpZAFf0rV1lloKoeIfbCs8QXzDjyOWAN0C90STWfK03SJTzMSTyaWYJRgK0vFQd12rp2P9gdXpqU/0XIpwtHZJyytlptegm/zW9m8MV3m26r6m7RwT21QCTy54RHjlhSq4Bo7AlnY0TH869XRIvjTj9D11Sm6vAWBPcZ87r4Ew0DzfY++njj/PWWNw2Xquxp45mqs8TWyfzctZQ9tB06+qzuGB7neXsban3k/kpcM6VfJiSIMkhNNVfKEQDFyXKdBtm3X9MNjUc8fI/HiJs+hLk/6BFDaM8e4WlczdB42g/m3Skq8+IRobTUMGY3TNzHB4pNNiUF5xm6YsmIf7JHboHsBhBWh/Z7j9TI5RdDm+qQD84BGXULJPEBh43mD68bCxqcNbjiKkRQarfkHOGmOGfc9m5BI0LyExbm+sqzWhSjq2RH9Y/AJG9Q7VdyS1JAzbXV//7/FY6GJZoyj4nVM9mp9Ko+5izrIFfMBLNChd7zt2ubfjum3Fz4p8g=
  template:
    metadata:
      name: sonarr
      namespace: media-server
    type: Opaque
